# Generated by Django 2.2.16 on 2021-08-14 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_title_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-pk',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('-pk',), 'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
